using System.Collections.Frozen;
using System.Collections.Immutable;
using System.IO.Hashing;
using System.Runtime.CompilerServices;
using System.Text;

namespace VehicleTaxonomy.Domain.Tests;

/// <summary>
/// Utility for creating strings that are both human-readable and uniquely scoped. The utility supports
/// shortening strings whilst keeping them readable and unique by replacing larger segments with a short
/// hash. This is typically most useful in integration tests when it's useful to have a unique but
/// human-readable string scoped to the test via the class and method name. This can make debugging test
/// data after concurrent test runs easier.
/// </summary>
public static class ScopedString
{
    private static readonly ScopedStringOptions _options = new()
    {
        Delimiter = "_",
        StopWords = ["Tests"],
        ReplacementPhrases = new Dictionary<string, string>
        {
            { "CommandHandler", "CH" },
            { "QueryHandler", "QH" }
        }.ToFrozenDictionary()
    };

    /// <summary>
    /// Combines <paramref name="parts" /> into a single string, compressing the output by
    /// running any configured stop word removals or replacements. The result is limited in
    /// size to <paramref name="maxLength" />. If the generated name is too long it is compressed
    /// by removing characters from the middle of the string and appending a unique hash generated from
    /// the original value e.g. 'MyClass-MyMethod-ShortHash'.
    /// </summary>
    /// <param name="maxLength">The maximum length of the returned string.</param>
    /// <param name="parts">A set of strings that uniquely represent the required scope.</param>
    public static string Format(int maxLength, params IReadOnlyCollection<string> parts)
    {
        var formattedString = Format(parts);
        if (formattedString.Length <= maxLength)
        {
            return formattedString;
        }

        var hash = Hash(string.Join(_options.Delimiter, parts));
        var delimiterChars = _options.Delimiter.Length * 2;
        var charsToRemove = formattedString.Length - maxLength + hash.Length + delimiterChars;

        if (charsToRemove > formattedString.Length)
        {
            // The max length limit is shorter than the hash so
            // best we can do is return a subset of the hash
            return hash[..maxLength];
        }

        // Remove characters from the middle, because the beginning is usually useful for
        // grouping and the end is often unique between similar variants.
        var midpoint = (formattedString.Length - charsToRemove) / 2;
        var prefix = formattedString[..midpoint];
        var postfix = formattedString[(midpoint + charsToRemove)..];
        var result = $"{prefix}{_options.Delimiter}{postfix}{_options.Delimiter}{hash}";

        return result;
    }

    /// <summary>
    /// Combines <paramref name="parts" /> into a single string, compressing the output by
    /// running any configured stop word removals or replacements.
    /// </summary>
    /// <param name="parts">A set of strings that uniquely represent the required scope.</param>
    public static string Format(params IReadOnlyCollection<string> parts)
    {
        var formattedString = string.Join(_options.Delimiter, parts.Select(FormatPart));

        return formattedString;

        static string FormatPart(string part)
        {
            foreach (var replacementPhrase in _options.ReplacementPhrases)
            {
                part = part.Replace(replacementPhrase.Key, replacementPhrase.Value, StringComparison.Ordinal);
            }

            foreach (var stopWord in _options.StopWords)
            {
                part = part.Replace(stopWord, string.Empty, StringComparison.Ordinal);
            }

            return part;
        }
    }

    /// <summary>
    /// Generates a string that is scoped to the file and method name of the callee, applying any
    /// configured stop word removals or phrase replacements e.g. 'MyClass-MyMethod'.
    /// </summary>
    /// <param name="callerMemberName">Callee member name to scope to, which is automatically generated by default.</param>
    /// <param name="callerFilePath">
    /// File path of the callee, which is used to get the file name to scope to. This is
    /// automatically generated by default.
    /// </param>
    public static string FromMethodName(
        [CallerMemberName] string callerMemberName = "",
        [CallerFilePath] string callerFilePath = "")
    {
        var fileName = Path.GetFileNameWithoutExtension(callerFilePath);

        return Format(fileName, callerMemberName);
    }

    /// <summary>
    /// Generates a fairly unique string that is scoped to the file and method name of the callee, limited
    /// in size to <paramref name="maxLength" />. If the generated name is too long it is compressed
    /// by removing characters from the middle of the string and appending a unique hash generated from
    /// the original value e.g. 'MyClass-MyMethod-ShortHash'.
    /// </summary>
    /// <param name="maxLength">The maximum length of the returned string.</param>
    /// <param name="callerMemberName">Callee member name to scope to, which is automatically generated by default.</param>
    /// <param name="callerFilePath">
    /// File path of the callee, which is used to get the file name to scope to. This is
    /// automatically generated by default.
    /// </param>
    public static string FromMethodName(
        int maxLength,
        [CallerMemberName] string callerMemberName = "",
        [CallerFilePath] string callerFilePath = "")
    {
        var fileName = Path.GetFileNameWithoutExtension(callerFilePath);

        return Format(maxLength, fileName, callerMemberName);
    }

    /// <summary>
    /// Generates a short hash from the specified string. We don't need to worry
    /// too much about uniqueness and collisions because the hash is combined with
    /// parts of the original string, and the number of hashes we need to generate
    /// for any set of tests is limited.
    /// </summary>
    private static string Hash(string stringToHash)
    {
        var hashAsBytes = Crc32.Hash(Encoding.UTF8.GetBytes(stringToHash));
        var hashAsString = Convert.ToBase64String(hashAsBytes)
            .Replace("=", string.Empty)
            .Replace("/", "-");

        return hashAsString;
    }

    private record ScopedStringOptions
    {
        /// <summary>
        /// The delimiter to put between segments of the string, making the result slightly longer
        /// but more human-readable. By default, no delimiter is used.
        /// is used.
        /// </summary>
        public string Delimiter { get; init; } = string.Empty;

        /// <summary>
        /// A collection of unimportant words to remove from the output string to help make it shorter.
        /// Word replacement is case-sensitive e.g. "And", "When", "Tests".
        /// </summary>
        public IReadOnlyCollection<string> StopWords { get; set; } = [];

        /// <summary>
        /// Words or phases to be replaced with a shorter alternative e.g. "CommandHandler" -> "CH".
        /// </summary>
        public IReadOnlyDictionary<string, string> ReplacementPhrases { get; set; } =
            ImmutableDictionary<string, string>.Empty;
    }
}
