services:
    cosmosdb:
        container_name: cosmosdb
        image: "mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest"
        environment:
          - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
        ports:
            - "8081:8081"
            - "10250-10255:10250-10255"
        volumes:
            -  vol_cosmos:/data/db
        
volumes:
    vol_cosmos: