<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="VehicleTaxonomy.Infrastructure.Tests" />
  </ItemGroup>
	<ItemGroup>
		<PackageReference Include="Azure.Storage.Blobs" Version="12.27.0" />
		<PackageReference Include="Microsoft.Azure.Cosmos" Version="3.57.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="Sep" Version="0.12.2" />
		<PackageReference Include="Sqids" Version="3.2.0" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

</Project>
